/**
 * Pure formatting helpers for exports (CSV / HTML for PDF). No native imports -> unit-testable.
 */
import type { Expense } from './cost-tracking';

export function csvCell(value: string | number | undefined | null): string {
  const str = value === undefined || value === null ? '' : String(value);
  return /[",\n\r]/.test(str) ? `"${str.replace(/"/g, '""')}"` : str;
}

export function escapeHtml(value: string | number | undefined | null): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

function isoDate(d: Date | string): string {
  const date = new Date(d);
  return Number.isNaN(date.getTime()) ? '' : date.toISOString().slice(0, 10);
}

export function buildExpensesCsv(expenses: Expense[]): string {
  const headers = ['Date', 'Category', 'Description', 'Amount', 'Currency', 'Recurring'];
  const rows = expenses.map(e => [
    isoDate(e.date), e.category, e.description, e.amount.toFixed(2), e.currency, e.recurring ? 'yes' : 'no',
  ]);
  return [headers.join(','), ...rows.map(r => r.map(csvCell).join(','))].join('\n');
}

export function generateExpensesHTML(expenses: Expense[], title = 'Expense Report', generatedAt = new Date()): string {
  const total = expenses.reduce((s, e) => s + e.amount, 0);
  const byCategory = new Map<string, number>();
  for (const e of expenses) byCategory.set(e.category, (byCategory.get(e.category) ?? 0) + e.amount);
  const currency = expenses[0]?.currency ?? '';
  const sorted = [...expenses].sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${escapeHtml(title)}</title>
<style>
body{font-family:Arial,sans-serif;margin:32px;color:#333}
h1{color:#10B981;border-bottom:3px solid #10B981;padding-bottom:8px}
table{border-collapse:collapse;width:100%;margin:16px 0}
th,td{border-bottom:1px solid #ddd;padding:6px 8px;text-align:left;font-size:13px}
th{background:#f0fdf4}
td.num,th.num{text-align:right}
.total{font-size:18px;font-weight:bold;margin-top:12px}
.footer{margin-top:32px;color:#666;font-size:12px;text-align:center}
</style></head><body>
<h1>${escapeHtml(title)}</h1>
<p>Generated ${escapeHtml(isoDate(generatedAt))} &middot; ${expenses.length} entries</p>
<h2>By category</h2>
<table><tr><th>Category</th><th class="num">Amount</th></tr>
${[...byCategory.entries()].map(([c, v]) => `<tr><td>${escapeHtml(c)}</td><td class="num">${v.toFixed(2)} ${escapeHtml(currency)}</td></tr>`).join('')}
</table>
<h2>All expenses</h2>
<table><tr><th>Date</th><th>Category</th><th>Description</th><th class="num">Amount</th></tr>
${sorted.map(e => `<tr><td>${escapeHtml(isoDate(e.date))}</td><td>${escapeHtml(e.category)}</td><td>${escapeHtml(e.description)}</td><td class="num">${e.amount.toFixed(2)} ${escapeHtml(e.currency)}</td></tr>`).join('')}
</table>
<div class="total">Total: ${total.toFixed(2)} ${escapeHtml(currency)}</div>
<div class="footer">Generated by GrowMaster AI</div>
</body></html>`;
}
